### ISSUE TITLE
Training is very slow on CO3D-V1

### ISSUE THREAD

**Issue by ZezhouCheng** [jasonyzhang/relpose#2]
Thanks for sharing the code, and congrats on the awesome work!

I'm trying to retrain the model on the CO3D-V1, and I can reproduce the results.  However, I found that it took about 6 days to train the model for 200K iterations on four 2080ti GPUs. I tried two different machines and many other tricks to speed up the training, but I still could not finish the training (400K iterations by default) in 2 days (the training time mentioned in the paper).

The data loading part seems to be the bottleneck. Have you encountered this issue in your experiments?

**Comment by jasonyzhang** [comment]
Hi,

That definitely sounds like a data bottleneck. Is your data on a hard disk by any chance? Ideally, you want the training images to be on the fastest storage possible. Since CO3D is massive, you can copy just the images to SSD/NVME. For CO3Dv2, this is about 270GB, and probably smaller for CO3Dv1. I added a simple script for doing this [here](https://github.com/jasonyzhang/relpose/blob/main/preprocess/copy_co3d.py). An additional optimization that can be done is to pre-resize/crop all the images since the majority of the CPU cycles done by the dataloader is actually just image resizing. Let me know if you want help with this.

Have you also tried changing the number of workers? It may need to be tuned to your system. https://github.com/jasonyzhang/relpose/blob/e96c643341d97dfda4921ac19fb272a1bb77c65a/relpose/trainer.py#L63-L65

Finally, we also have a follow-up work that has better results that you may want to check out: https://github.com/amyxlase/relpose-plus-plus
RelPose++ is trained with DDP which should also be a lot more efficient than RelPose training.

Best,
Jason

**Comment by ZezhouCheng** [comment]
Thank you for the quick and detailed reply, Jason! They are very helpful. The training remains slow when I move the data to SSD from HDD. I have also played with different numbers of workers in the data loader. Adding more workers usually has faster training but reaches a plateau quickly (e.g. 8 workers per GPU).  Did you pre-resize / crop the images in your experiments? I'm curious about how to finish the training within 2 days with the same preprocessing steps as yours so that I can find out the exact reasons why my training is so slow.

**Comment by jasonyzhang** [comment]
I'm not really sure what else it could be. Do you have sufficient CPUs on the machine? Otherwise, I'm not sure what else it could be. I could send you some tensorboards if you need something to compare to.

I did not pre-resize/pre-crop images for RelPose. I only discovered this trick a couple of days ago. But I think it would help quite a bit.

**Comment by ZezhouCheng** [comment]
The resizing process is indeed the bottleneck. On average, it takes around 0.04 seconds to resize one CO3D image, as most images are high-resolution (e.g. > 1000x1000). We do have sufficient CPUs (48 cores per node), but probably our cluster is shared by many people, which may create a high CPU load. Anyway, your suggestions are really helpful. Thank you, Jason!
